#!/bin/bash

logdest="/tmp/nettest-log"
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

touch ${logdest} && chown ${6}:${7} ${logdest}

echo -e "[$(TZ=${5} date +%D" "%H:%M" "%Z)] Monitoring network records, checks every ${4} seconds\nCurrent external IP is $(curl -s "https://api.ipify.org")"
echo -e "[$(TZ=${5} date +%D" "%H:%M" "%Z)] Monitoring network records, checks every ${4} seconds\nCurrent external IP is $(curl -s "https://api.ipify.org")" >> ${logdest}

while :;do
  sleep ${4}
  #Random sleep so multiple site updates doesn't cause API to timeout
  sleep $((RANDOM % 15 + 1))
  myip=`curl -s "https://api.ipify.org"`
  echo "[$(TZ=${5} date +%D" "%H:%M" "%Z)] Current external IP - ${myip}"
  echo "[$(TZ=${5} date +%D" "%H:%M" "%Z)] Current external IP - ${myip}" >> ${logdest}
done
